language: cpp
sudo: true
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - cmake

before_install:
  - echo $LANG
  - echo $LC_ALL
  - export CXX="g++-5" CC="gcc-5";
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots;
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev

script: 
  - ./compile.sh