language: cpp
sudo: true
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - cmake

before_install:
  - echo $LANG
  - echo $LC_ALL
  - export CXX="g++" CC="gcc";
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl2-dev

script: 
  - ./compileAndRun.sh