language: cpp
sudo: false
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - cmake
      - libsdl2-dev

before_install:
  - echo $LANG
  - echo $LC_ALL
  - export CXX="g++-4.8" CC="gcc-4.8";

script: 
  - ./compileAndRun.sh