#ifndef BITMAP_TYPE_HPP_
#define BITMAP_TYPE_HPP_


enum class BitmapType
{
    BRICK_RED,
    BUSH_LEFT,
    BUSH_MIDDLE,
    BUSH_RIGHT,
    COIN_PARTICLE_0,
    COIN_PARTICLE_1,
    COIN_PARTICLE_2,
    COIN_PARTICLE_3,
    GROUND_RED,
    HILL_LEFT,
    HILL_MIDDLE,
    HILL_MIDDLE_2,
    HILL_MIDDLE_3,
    HILL_RIGHT,
    HILL_TOP,
    GOOMBA_WALK_0,
    GOOMBA_WALK_1,
    GOOMBA_SQUASHED,
    MARIO_JUMPING,
    MARIO_RUNNING_0,
    MARIO_RUNNING_1,
    MARIO_RUNNING_2,
    MARIO_SLIDING,
    MARIO_STANDING,
    MUSHROOM,
    QUESTIONBLOCK_0,
    QUESTIONBLOCK_1,
    QUESTIONBLOCK_2,
    QUESTIONBLOCK_USED,
    SQUID_0,
    SQUID_1,
    PIPE_TOP_LEFT,
    PIPE_TOP_RIGHT,
    PIPE_BOTTOM_LEFT,
    PIPE_BOTTOM_RIGHT,
    SMALL_BRICK_1,
    SMALL_BRICK_2
};

#endif  // BITMAP_TYPE_HPP_